# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gatekeeper}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Dinn"]
  s.date = %q{2010-01-16}
  s.description = %q{Connects any Rack-compatible app to a Hot Ink single sign on server.}
  s.email = %q{chrisgdinn@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "gatekeeper.gemspec",
     "lib/gatekeeper.rb",
     "lib/gatekeeper/helpers/authentication.rb",
     "lib/gatekeeper/helpers/rack.rb",
     "lib/gatekeeper/middleware.rb",
     "lib/gatekeeper/sso.rb",
     "spec/gatekeeper_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/chrisdinn/gatekeeper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Connects any Rack-compatible app to a Hot Ink single sign on server.}
  s.test_files = [
    "spec/gatekeeper_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-openid>, [">= 2.1.7"])
      s.add_runtime_dependency(%q<rack-openid>, [">= 0.2.1"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<ruby-openid>, [">= 2.1.7"])
      s.add_dependency(%q<rack-openid>, [">= 0.2.1"])
      s.add_dependency(%q<sinatra>, [">= 0.9.2"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<ruby-openid>, [">= 2.1.7"])
    s.add_dependency(%q<rack-openid>, [">= 0.2.1"])
    s.add_dependency(%q<sinatra>, [">= 0.9.2"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

